### ISSUE TITLE
Custom plugin throws error when analyzing endpoint

### ISSUE THREAD

**Issue by aaronhmiller** [yesinteractive/kong-map#1]
`Notice: Undefined index: signalsciences in /app/controllers/fsl_controllers.php on line 418`

Not sure if the audit log error is related, but see these in the Kong Logs:

```172.20.0.5 - - [22/Oct/2020:04:09:23 +0000] "GET /default/plugins HTTP/1.1" 200 94937 "-" "Fresh Squeezed Limonade (https://github.com/yesinteractive/fsl)"
2020/10/22 04:09:23 [error] 24#0: *22944 [kong] audit_log.lua:229 could not deserialize/serialize JSON payload to table: bad argument #1 to '?' (string expected, got nil) while logging request, client: 172.20.0.5, server: kong_admin, request: "GET /default/plugins HTTP/1.1", host: "kong-ent1:8001"```

**Comment by nikirago** [comment]
Hey @aaronhmiller . Right now it doesn't have a way to figure out the priority of custom plugins so it can't find an index for them to rank against plugins. So custom plugins are being thrown at the end right now. I'll update to squash the PHP Notice for now. I don't think the audit log error is related to this error unless its being triggered by an admin api call or deck pull?

**Comment by nikirago** [comment]
This has been resolved in new docker image uploaded to Dockerhub.io

**Comment by aaronhmiller** [comment]
tested the new version and thank you, the PHP error is gone!
