### ISSUE TITLE
deploy kongmap on kubernetes

### ISSUE THREAD

**Issue by sulaimantok** [yesinteractive/kong-map#18]
Sorry i'm a bit confused, hoping to get enlightenment, I want to deploy kongmap over kubernetes, but because in the latest version of kong there is no Admin API, I don't understand how to communicate and how to deploy kongmap over Kube / openshift, thank you

**Comment by kadtendulkar** [comment]
Hey I'm working on same, i need to deploy kong map in kubernetes using yaml file. After deploying it and accessing via the load balancer ip address, i get as "no cluster was defined in config or is missing configuration items. See instructions"

Although i have added the env variable KONG_CLUSTERS in the yaml.

Following is the value.
env:
- name: KONG CLUSTERS
  value: '{ "my open source cluster": { "kong_admin_api_url": "http://kong-kong-admin.kong .svc.cluster.local:8001", "kong_edit_config": "true", "kong_ent": "false", "kong_ent_token": "null", "kong_ent_token_name": "null", "kong ent_manager_url": "null" }}'

If you have deployed it and working fine. Please guide me through it.
Thanks

**Comment by kadtendulkar** [comment]
Hello. i found the solution.. instead of the name of env KONG_CLUSTERS write KONGMAP_CLUSTERS_JSON

Let me know if you facing any issues.

**Comment by sulaimantok** [comment]
sorry for just replying, yes for the issue you are experiencing you can use ENV KONGMAP_CLUSTERS_JSON. The KONG_CLUSTERS variable is only used to store the kongmap config, and when deploying it uses the KONGMAP_CLUSTERS_JSON env. Like this "KONGMAP_CLUSTERS_JSON=$KONG_CLUSTERS" for example
