### ISSUE TITLE
View UI KongMap 

### ISSUE THREAD

**Issue by afrizalauliaazhari** [yesinteractive/kong-map#23]
![image](https://user-images.githubusercontent.com/6578286/142601906-d995c661-6fd9-4a8d-8b0c-817d615d516c.png)
![image](https://user-images.githubusercontent.com/6578286/142602086-8739f95e-e3b1-40d8-b139-9f1d12d687fa.png)

Please info for my issue
and step by step for problem solved

Thanks

**Comment by cybrrnick** [comment]
Hello, please upgrade to the latest version. Also, what are you using for a JSON configuration for the KONG_CLUSTERS  env variable? That error means the JSON is not formatted correctly or is missing items or missing all together.
