### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by bonndan** [yesinteractive/kong-map#8]
Hi,

interesting project, but where is the source code?

**Comment by linuxbandit** [comment]
I second the request

**Comment by nikirago** [comment]
Will be releasing the full code soon. For now you can view the code in the /app directly of the distributed docker container.

**Comment by linuxbandit** [comment]
Hello! Is there an update?

**Comment by eduardobaitello** [comment]
I'm looking for the source too  🙈

**Comment by landorg** [comment]
https://github.com/landorg/kong-map
If someone wants to write a Dockerfile I'm acceping PRs ;)

**Comment by nikirago** [comment]
I will be adding the code in the next week. Sorry took so long.

**Comment by cronventis** [comment]
Good thing.. Then maybe development can continue... This project seems stuck a bit..

**Comment by nikirago** [comment]
Source code added. will rebuild docker image shortly with the new code updates.
